import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const reboto = localFont({
  src: [
    { 
      path:'../config/fonts/Roboto/static/Roboto-Medium.ttf'
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${reboto.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
